remote_theme: fongandrew/hydeout
title: Stastic editor
tagline: Test of stastic to admin a Jekyll site
description: >-
  A <a href="https://stastic.net" target="_blank">Stastic</a> editor for <a
  href="http://jekyllrb.com" target="_blank">Jekyll</a>, refreshed.
url: 'https://fongandrew.github.io'
baseurl: /recalcitant_artist
author:
  name: Andrew Fong
  url: 'https://twitter.com/fongandrewc'
hydeout:
  repo: 'https://github.com/fongandrew/hydeout'
  version: null
disqus:
  shortname: null
google_analytics: null
